nav:
    - Introduction: index.md
    - Eli-Bendersky-thegreenplace-The-Expression-Problem-and-its-solutions: Eli-Bendersky-thegreenplace-The-Expression-Problem-and-its-solutions
    - Synthesizing-Object-Oriented-and-Functional-Design-to-Promote-Re-Use: Synthesizing-Object-Oriented-and-Functional-Design-to-Promote-Re-Use
    