nav:
    - Introduction: index.md
    - Formal-and-formal-langugae: Formal-and-formal-langugae.md
    - Formal-language: Formal-language.md
    - Intermediate-language: Intermediate-language
    - Formal-grammar: Formal-grammar
    - Summary-of-theory: Summary-of-theory.md
