edit_uri: ''
extra_css:
- css/extra.css
markdown_extensions:
- toc:
    permalink: '#'
    separator: _
nav:
- Home: index.md
- Primer: Primer.md
- Mathematical-logic:
  - Introduction: Mathematical-logic/index.md
- Formal-language:
  - Introduction: Formal-language/index.md
  - Description-and-language: Formal-language/Description-and-language.md
  - Formal-and-formal-langugae: Formal-language/Formal-and-formal-langugae.md
  - Language-and-grammar: Formal-language/Language-and-grammar.md
  - Formal-language: Formal-language/Formal-language.md
  - Formal-grammar:
    - Formal-grammar: Formal-language/Formal-grammar/wikipedia-Formal-grammar.md
    - Production: Formal-language/Formal-grammar/wikipedia-Production(computer-science).md
    - Chomsky-hierarchy:
      - Chomsky-hierarchy: Formal-language/Formal-grammar/Chomsky-hierarchy/wikipedia-Chomsky-hierarchy.md
      - Type-0:
        - Recursively-enumerable-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-0/wikipedia-Recursively-enumerable-language.md
        - Turinig-machine:
          - Introduction: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-0/Turinig-machine/index.md
          - What-is-a-Turing-machine: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-0/Turinig-machine/What-is-a-Turing-machine.md
          - Turing-machine: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-0/Turinig-machine/Turing-machine.md
          - wikipedia-Turing-machine: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-0/Turinig-machine/wikipedia-Turing-machine.md
      - Type-1:
        - Context-sensitive-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-1/wikipedia-Context-sensitive-language.md
      - Type-2:
        - Context-free-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-2/wikipedia-Context-free-language.md
        - Automaton: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-2/Automaton.md
      - Type-3:
        - Regular-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-3/wikipedia-Regular-language.md
        - Automaton: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-3/Automaton.md
        - Regular-expression:
          - Regular-expression: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-3/Regular-expression/wikipedia-Regular-expression.md
          - Thompson's-construction: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-3/Regular-expression/wikipedia-Thompson's-construction.md
          - Regex-Engine: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-3/Regular-expression/Regex-Engine.md
    - Parsing-Expression-Grammars:
      - Parsing-expression-grammar: Formal-language/Formal-grammar/Parsing-Expression-Grammars/Parsing-expression-grammar.md
- Theory-of-computation:
  - index: Theory-of-computation/index.md
  - Theory-of-computation: Theory-of-computation/Theory-of-computation.md
plugins:
- search
repo_url: https://github.com/dengking/automata-and-formal-language
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: automata-and-formal-language
site_url: https://dengking.github.io/automata-and-formal-language
theme:
  name: material
