edit_uri: ''
extra_css:
- css/extra.css
markdown_extensions:
- toc:
    baselevel: 2
    permalink: '#'
    separator: _
- admonition
- def_list
- mdx_gh_links:
    repo: mkdocs
    user: mkdocs
nav:
- Home: index.md
- Introduction:
  - Introduction: Introduction/index.md
- Theory-framework:
  - Introduction: Theory-framework/index.md
  - Formal-language:
    - Introduction: Theory-framework/Formal-language/index.md
    - Description-and-language: Theory-framework/Formal-language/Description-and-language.md
    - Formal-language: Theory-framework/Formal-language/wikipedia-Formal-language.md
    - Formal-system: Theory-framework/Formal-language/wikipedia-Formal-system.md
    - Formal-grammar:
      - Formal-grammar: Theory-framework/Formal-language/Formal-grammar/wikipedia-Formal-grammar.md
      - Production: Theory-framework/Formal-language/Formal-grammar/wikipedia-Production(computer-science).md
      - BNF: Theory-framework/Formal-language/Formal-grammar/wikipedia-Backus-Naur-form.md
plugins:
- search
repo_url: https://github.com/dengking/automata-and-formal-language
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: automata-and-formal-language
site_url: https://dengking.github.io/automata-and-formal-language
theme:
  highlightjs: true
  hljs_languages:
  - yaml
  - django
  name: readthedocs
