edit_uri: ''
extra_css:
- css/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    separator: '#'
- admonition
- def_list
- mdx_gh_links:
    repo: mkdocs
    user: mkdocs
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- Home: index.md
- Language:
  - Introduction: Language/index.md
  - Classification:
    - Introduction: Language/Classification/index.md
    - Domain-specific-language:
      - Introduction: Language/Classification/Domain-specific-language/index.md
      - martinfowler-Domain-Specific-Languages:
        - Introduction: Language/Classification/Domain-specific-language/martinfowler-Domain-Specific-Languages/index.md
    - GPL-and-DSL: Language/Classification/GPL-and-DSL.md
    - Official-and-dialect: Language/Classification/Official-and-dialect.md
    - Host-and-embeded-and-meta: Language/Classification/Host-and-embeded-and-meta.md
  - Language-and-computation:
    - Introduction: Language/Language-and-computation/index.md
    - Language-for-structure:
      - Introduction: Language/Language-and-computation/Language-for-structure/index.md
      - Zephyr-ASDL:
        - Introduction: Language/Language-and-computation/Language-for-structure/Zephyr-ASDL/index.md
        - thegreenplace-Using-ASDL-to-describe-ASTs-in-compilers:
          - Introduction: Language/Language-and-computation/Language-for-structure/Zephyr-ASDL/thegreenplace-Using-ASDL-to-describe-ASTs-in-compilers/index.md
        - paper-The-Zephyr-Abstract-Syntax-Description-Language:
          - Introduction: Language/Language-and-computation/Language-for-structure/Zephyr-ASDL/paper-The-Zephyr-Abstract-Syntax-Description-Language/index.md
    - Structure-of-language:
      - Grammar: Language/Language-and-computation/Structure-of-language/Language-and-grammar.md
  - Language-in-discipline: Language/Language-in-discipline.md
  - Expressive-power:
    - Introduction: Language/Expressive-power/index.md
  - Language-agnostic:
    - Introduction: Language/Language-agnostic/index.md
- Formal-language:
  - Introduction: Formal-language/index.md
  - Formal-and-formal-langugae:
    - Introduction: Formal-language/Formal-and-formal-langugae/index.md
  - wikipedia-Formal-language:
    - Introduction: Formal-language/wikipedia-Formal-language/index.md
  - Intermediate-language:
    - Introduction: Formal-language/Intermediate-language/index.md
  - Formal-grammar:
    - Formal-grammar:
      - Introduction: Formal-language/Formal-grammar/wikipedia-Formal-grammar/index.md
    - Production:
      - Introduction: Formal-language/Formal-grammar/Production(computer-science)/index.md
    - Chomsky-hierarchy:
      - Introduction: Formal-language/Formal-grammar/Chomsky-hierarchy/index.md
      - Type-0:
        - Recursively-enumerable-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-0/wikipedia-Recursively-enumerable-language.md
      - Type-1:
        - Context-sensitive-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-1/wikipedia-Context-sensitive-language.md
      - Type-2:
        - Context-free-language: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-2/Context-free-language.md
        - Pushdown-automaton:
          - Introduction: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-2/Pushdown-automaton/index.md
      - Type-3:
        - Introduction: Formal-language/Formal-grammar/Chomsky-hierarchy/Type-3/index.md
      - "\u5BF9\u6BD4\u5206\u6790":
        - Introduction: "Formal-language/Formal-grammar/Chomsky-hierarchy/\u5BF9\u6BD4\
            \u5206\u6790/index.md"
    - Parsing-Expression-Grammars:
      - Introduction: Formal-language/Formal-grammar/Parsing-Expression-Grammars/index.md
  - Summary-of-theory:
    - Introduction: Formal-language/Summary-of-theory/index.md
- Formal-language-processing:
  - Introduction: Formal-language-processing/index.md
  - Formal-language-processor:
    - Introduction: Formal-language-processing/Formal-language-processor/index.md
  - Pattern:
    - Introduction: Formal-language-processing/Pattern/index.md
    - Composite-pattern:
      - Introduction: Formal-language-processing/Pattern/Composite-pattern/index.md
    - Interpreter-pattern:
      - Introduction: Formal-language-processing/Pattern/Interpreter-pattern/index.md
    - Translator-Pattern:
      - Introduction: Formal-language-processing/Pattern/Translator-Pattern/index.md
- Regular-language:
  - Introduction: Regular-language/index.md
  - Regular-expression:
    - Introduction: Regular-language/Regular-expression/index.md
    - Regex-Engine:
      - Introduction: Regular-language/Regular-expression/Regex-Engine/index.md
      - Thompson's-construction:
        - Introduction: Regular-language/Regular-expression/Regex-Engine/Thompson's-construction/index.md
      - Powerset-construction:
        - Introduction: Regular-language/Regular-expression/Regex-Engine/Powerset-construction/index.md
- Mathematical-logic:
  - Introduction: Mathematical-logic/index.md
  - Propositional-calculus: Mathematical-logic/Propositional-calculus.md
  - Axiom-schema: Mathematical-logic/Axiom-schema.md
- Symbolic-computation:
  - Introduction: Symbolic-computation/index.md
  - What-is-symbol:
    - Introduction: Symbolic-computation/What-is-symbol/index.md
  - Symbolic-computation:
    - Introduction: Symbolic-computation/Symbolic-computation/index.md
    - risc-Studying-Symbolic-Computation:
      - Introduction: Symbolic-computation/Symbolic-computation/risc-Studying-Symbolic-Computation/index.md
  - Symbolic-programming:
    - Introduction: Symbolic-computation/Symbolic-programming/index.md
    - utexas-CS-378-Symbolic-Programming:
      - Introduction: Symbolic-computation/Symbolic-programming/utexas-CS-378-Symbolic-Programming/index.md
  - Symbol-expression:
    - Introduction: Symbolic-computation/Symbol-expression/index.md
  - Expression-oriented-language:
    - Introduction: Symbolic-computation/Expression-oriented-language/index.md
  - Expression-problem:
    - Introduction: Symbolic-computation/Expression-problem/index.md
    - Extended-visitor-pattern:
      - Introduction: Symbolic-computation/Expression-problem/Extended-visitor-pattern/index.md
      - eli.thegreenplace-The-Expression-Problem-and-its-solutions:
        - Introduction: Symbolic-computation/Expression-problem/Extended-visitor-pattern/eli.thegreenplace-The-Expression-Problem-and-its-solutions/index.md
      - Synthesizing-Object-Oriented-and-Functional-Design-to-Promote-Re-Use:
        - Introduction: Symbolic-computation/Expression-problem/Extended-visitor-pattern/Synthesizing-Object-Oriented-and-Functional-Design-to-Promote-Re-Use/index.md
    - Object-Algebra:
      - Introduction: Symbolic-computation/Expression-problem/Object-Algebra/index.md
  - Computer-algebra:
    - Introduction: Symbolic-computation/Computer-algebra/index.md
- LaTeX:
  - Introduction: LaTeX/index.md
  - LaTeX-under:
    - Introduction: LaTeX/LaTeX-under/index.md
- Dyck-language:
  - Introduction: Dyck-language/index.md
plugins:
- search
repo_url: https://github.com/dengking/Language
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: Language
site_url: https://dengking.github.io/Language
theme:
  name: material
