nav:
    - Regular-expression: wikipedia-Regular-expression.md
    - Thompson's-construction: wikipedia-Thompson's-construction.md
    - Regex-Engine: Regex-Engine.md
    - Powerset-construction: wikipedia-Powerset-construction.md