nav:
    - Introduction: index.md
    - The-Expression-Problem-and-its-solutions: The-Expression-Problem-and-its-solutions
    - Synthesizing-Object-Oriented-and-Functional-Design-to-Promote-Re-Use: Synthesizing-Object-Oriented-and-Functional-Design-to-Promote-Re-Use