nav:
    - Home: index.md
    - Language: Language
    - Grammar: Grammar
    - Mathematical-logic: Mathematical-logic
    - Formal-language: Formal-language
    - Theory-of-computation: Theory-of-computation